# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77a6c1609bef6c3624b6f386791bc81bd37b5df529ad7ef87b1022c72f2b1bfee80023ffb0f642710f42307a04c34a1b573f1bd4ff100a2631d76deecb7f9f48

test:
  secret_key_base: fb123d74fd53a43262ab112988295b830a5a12c6eed37666da6b20fe3c5553060cbc7543cba43cce7ca7549181cd6fa8f58967e4f4c596a2d3412cf8ec46f4ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
